### ISSUE TITLE
what to add in JSON RPC provider URL

### ISSUE THREAD

**Issue by jitjabadmin** [jfrazier-eth/ethereum-mint-bot#2]
hi this is a great project and i was looking for something like this for a while. 

i just have a very small question

what to add in JSON RPC provider URL

whenever i add a url it gives me UnhandledPromiseRejectionWarning: Error: failed to get contract abi. NOTOK-Missing/Invalid API Key, rate limit of 1/5sec applied.

also in website when i add a contract address and submit nothing happens. will it be possible for you to create a detailed documentation

really appreciate that  
thanks

**Comment by jfrazier-eth** [comment]
Hi, it's actually still in early development. I'm hoping to have it complete in about a week or two. In the meantime, I will make sure to add a note so people don't try to use it yet.

**Comment by jitjabadmin** [comment]
Thanks for your quick response. 

I wasn't aware of that. Anyway it's a great project and I really love to see it grow.

Good luck
